/**
 Copyright (c) 2019 OPeNDAP, Inc.
 Please read the full copyright statement in the file LICENSE.

 Authors: 
	James Gallagher	 <jgallagher@opendap.org>
    Samuel Lloyd	 <slloyd@opendap.org>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

 You can contact OPeNDAP, Inc. at PO Box 112, Saunderstown, RI. 02874-0112.
*/

/**
 * Document class means that it is DB entity.
 * It should contains getter and setters which are automatically generated by Lombok framework.
 */
package org.opendap.harvester.entity.document;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Document
@Builder
public class HyraxInstance extends BaseEntity {	
    @Getter @Setter
    private String name;
    @Getter @Setter
    private String reporterUrl;
    @Getter @Setter @Builder.Default
    private Long ping = 0L;
    @Getter @Setter @Builder.Default
    private Integer log = 0;
    @Getter @Setter
    private String versionNumber;
    @Getter @Setter
    private String serverVersionNumber;
    @Getter @Setter
    private String reporterVersionNumber;
    @Getter @Setter
    private LocalDateTime registrationTime;
    @Getter @Setter
    private LocalDateTime lastAccessTime;
    @Getter @Setter
    private LocalDateTime lastSuccessfulPull;
    @Getter @Setter
    private LocalDateTime reporterLastErrorTime;
    @Getter @Setter
    private LocalDateTime serverLastErrorTime;
    @Getter @Setter
    private LocalDateTime serverLastAccessTime;
    @Getter @Setter @Builder.Default
    private Boolean accessible = true;
    @Getter @Setter @Builder.Default
    private Boolean reporterRunning = true;
    @Getter @Setter @Builder.Default
    private Boolean serverRunning = true;
    @Getter @Setter
    private List<DownTimes> reporterDownTimes;
    @Getter @Setter
    private List<DownTimes> serverDownTimes;
    @Getter @Setter @Builder.Default
    private Boolean active = false;
    @Getter @Setter
    private UUID serverUUID;
    
    public void addStartToReporterDownTime(LocalDateTime start) {
    	if (reporterDownTimes == null) {
    		initReporterDownTime();
    	}
    	DownTimes dt = new DownTimes();
    	dt.start = start;
    	reporterDownTimes.add(dt);
    }
    
    public void addEndToReporterDownTime(LocalDateTime end) {
    	reporterDownTimes.get(reporterDownTimes.size() - 1).end = end;
    }
    
    public void addStartToServerDownTime(LocalDateTime start) {
    	if (serverDownTimes == null) {
    		initServerDownTime();
    	}
    	DownTimes dt = new DownTimes();
    	dt.start = start;
    	serverDownTimes.add(dt);
    }
    
    public void addEndToServerDownTime(LocalDateTime end) {
    	serverDownTimes.get(serverDownTimes.size() - 1).end = end;
    }
    
    public void initReporterDownTime() {
    	List<DownTimes> dts = new ArrayList<DownTimes>();
		reporterDownTimes = dts;
    }
    
    public void initServerDownTime() {
    	List<DownTimes> dts = new ArrayList<DownTimes>();
		serverDownTimes = dts;
    }
}

